# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webusers',
            name='img',
            field=models.FileField(null=True, upload_to='webusers/'),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='lname',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
